function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Jun-2018 19:22:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'Parent',axes1);

% Create xlabel
xlabel('Xaxis');

% Create ylabel
ylabel('yaxis');

% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend(axes1,'show');

